spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/home
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123
  rabbitmq:
    host: 127.0.0.1
    port: 5672  #15672 是http端口  5672是访问mq端口
    username: guest
    password: guest
    connection-timeout: 20000
server:
  port: 8081