spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/home
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123
server:
  port: 8081
